#+OPTIONS: toc:nil 
#+BEGIN_EXPORT html
---
layout: post
categories: [orgmode]
title: Blogging with Org mode and FastPages
description: Tutorial to setup Fastpages with org mode
---
#+END_EXPORT

#+TOC: headline 3

* Introduction

Jeremy and Rachel, esteemed founders of fastai, quote /Blogging is like Resume, only better/ in this [[https://www.fast.ai/2019/05/13/blogging-advice/][post]]. Blogging really is one of the best medium to learn while doing something, communicate and formulate ideas, and share knowledge with your peers and colleagues. Blogging for me addresses 3 main themes.

   1. Communication and Writing Skills
   2. Showcase of Technical Expertise
   3. Medium of learning and teachning 

With nbdev, fastai library and video courses; Fastai team has contributed some of the best material and tools for learning data science and programming in general. The top down learning style , with focus on learning the big picture by doing is an amazingly useful and productive technique especially for someone who is working full time. 

Fastpages is the recent addition in the same tradition of tools made available by FastAI team to new and practicing data scientist to facilitate there learning journey. It capitalizes on nbdev codebases, a python literate programming tool and github actions to enable blogging by jupyter notebook and markdown files.

My objective in this post is to showcase some of the minor changes which I have made which can enable me to use entire toolchain of fastpages to blog with emacs org mode along with notebook, markdown or word format. I also want to make a case for how powerful org mode really is ; and why it belongs IN A DATA SCIENTIST TOOLBOX; ALONGSIDE OTHER TOOLS MENTIONED ABOVE.

* COMMENT EMACS ORG-MODE: WHAT? WHY? HOW?

/BEFORE CAME JUPYTER, BEFORE CAME INTERNET AND EVEN BEFORE THERE WERE PERSONAL COMPUTERS.THERE WAS SOMETHING CALLED EMACS/


So what is org-mode? At the very basic level org mode or org format is a text markup defined for structured text editing. It is similar to markdown as it is defined in plaintext, priortizes readability and  has an human centric approach. But combination with emacs elisp system makes it insanely powerful. Instead of markup it is really a system of text editing which is highly extensible and infinetly programmable. With various open source plugins' it can be used like a notebook or frontend for latex report creation or even online presentations. 

Here are a list of example of things that you can do with it. 

   - *Blogging* - You can write a blog post like this. Since Emacs is insanely powerful for text editing you can do really fast typing.

   - *Literate Programming* - You can do literate programming just like jupyter notebooks, create latex reports, even write full fledged books.

   - *GTD, Task Manager, Todo* - You can use it as task manager, do project management, create to do list. Follow the recommendations of GTD managing your life in a text edit. And many many more things. A good set of references are in following playlist

   - *Youtube Playlist Embed* - This is a nice list of videos for org mode introduction.
   #+BEGIN_EXPORT html
   <div style="text-align: center;">
      <iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PLxc79l2wpbJYTI5rv2os7OoKQMqxReZpr" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
   </div>
   #+END_EXPORT

   - *Youtube Video Embed*- Similar to markdown approach
   
    #+begin_export html

    {% include youtube.html content='<a href="https://youtu.be/XfoYk_Z5AkI">https://youtu.be/XfoYk_Z5AkI</a>' %}

    #+end_export

   - Similar to markdown fastpages, you can invoke twitter liquid template to export twitter card
    
    #+begin_export html

    {% include twitter.html content="https://twitter.com/jakevdp/status/1204765621767901185?s=20" %}

    #+end_export

   - You can even convert an org file to a reveal presentation and integrate with FastPages.
